### PR TITLE
sync moderator by saml attribute

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by SamSaffron** [comment]
@vinothkannans how does this change look?

**Comment by vinothkannans** [comment]
Looks good to me. @sbernhard can you add some tests here?

**Comment by sbernhard** [comment]
sure @vinothkannans , but unfortunately, I'm not able to run the test. can you please have a look? or will the test run in github / travis (which would be great).

**Comment by vinothkannans** [comment]
The tests are passing now after a minor fix. Thanks for the contribution ❤️

**Comment by sbernhard** [comment]
thanks for fixing the issue. 
would be great if you can have a look at the other PR regarding fullName, too :)

**Comment by vinothkannans** [comment]
Sure, I will check that PR as soon as possible.

**Pull request merged**
