### PR TITLE
Support for overriding base_url using saml_base_url GlobalSetting

### PR DESCRIPTION
**Pull request by discoursehosting**

### CODE REVIEW

**Comment by ZogStriP** [comment]
Might be better to have a method that would be used everywhere else?

``` ruby
def self.saml_base_url
  GlobalSetting.try(:saml_base_url) || Discourse.base_url
end
```

**Comment by discoursehosting** [comment]
Sounds like a plan but I'm lacking a bit of Ruby knowledge here, if I add it as a method in plugin.rb is there any way I can access it from within SamlAuthenticator  ?

**Comment by eviltrout** [comment]
@discoursehosting You can't add it as a top level method in `plugin.rb` because those methods are not namespaced in a module.

However you could add the class method that regis suggested to `SamlAuthenticator` then you could call `SamlAuthenticator.saml_base_url` in any code to get that value.

**Comment by eviltrout** [comment]
I'm unfortunately going to have to close this as it's been open too long. We will accept a new PR for this.

**Pull request closed without merging**
