### PR TITLE
Allow to set name using saml attributes fullName or firstName + lastName

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by vinothkannans** [comment]
@sbernhard already you [can send `firstName` and `lastName` params](https://github.com/discourse/discourse-saml/blob/master/lib/saml_authenticator.rb#L34). Is it not working?

**Comment by sbernhard** [comment]
If I remember it correctly, the user-friendly name in the window to create the user was empty. The only thing which worked was to set the fullName.

**Comment by sbernhard** [comment]
Can you please verify @vinothkannans if firstName + lastName can be used, if auto_create_account is false? If I remember correctly, if firstName + lastName is set, the name in the popup which opens because auto_create_account, is still the uid. therefore I think, something like this PR is necessary.

**Comment by vinothkannans** [comment]
Sure, I will let you know once I checked it.

**Comment by eviltrout** [comment]
@vinothkannans bumping this as it's been almost two weeks.

**Comment by vinothkannans** [comment]
It's merged. @sbernhard thanks for your contribution and sorry for the delay.

**Pull request merged**
